# https://www.home-assistant.io/integrations/automation/

# My own handmade automations
automation manual: !include_dir_merge_list ../automations/

# Automations I create in the UI
automation ui: !include ../automations.yaml
