# Database monitoring using command_line integration
# https://www.home-assistant.io/integrations/command_line/
command_line:
  - sensor:
      name: Home Assistant Database Size
      command: "du -m home-assistant_v2.db | awk '{print $1}'"
      unit_of_measurement: MB
      scan_interval: 86400
