language: python
python:
  - "3.7"
before_install:
  - mv secrets.fake.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev 
  - mkdir tmp/
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./known_devices.yaml
  - touch ./secrets/fake_ssl_cert
  - touch ./secrets/fake_ssl_key
  - touch ./customize.yaml
  - touch ./google_calendar.yaml
  - mv secrets/home-assistant.fake.json secrets/home-assistant.json
install:
  - pip3 install homeassistant netdisco python-dateutil
  - hass --version
script:
  - hass -c . --script check_config
after_failure:
  - cat home-assistant.log
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
