language: python
python:
  - "3.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev 
  - touch ./fake_id_rsa
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./fake_cert.pem
  - touch ./known_devices.yaml
  - touch ./fake_ssl_cert
  - touch ./fake_ssl_key
  - mkdir tmp/
install:
  - pip3 install homeassistant netdisco python-dateutil
script:
  - hass -c . --script check_config
after_failure:
  - cat home-assistant.log