language: python
python:
  - "3.7"
before_install:
  - mv secrets.fake.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev 
  - touch ./fake_id_rsa
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./fake_cert.pem
  - touch ./known_devices.yaml
  - touch ./fake_ssl_cert
  - touch ./fake_ssl_key
  - touch ./fake.json
  - mkdir tmp/
  - mv secrets/home-assistant.fake.json secrets/home-assistant.json
install:
  - pip3 install homeassistant netdisco python-dateutil
script:
  - hass --version
  - hass -c . --script check_config | tee check.output
after_failure:
  - cat check.output | grep -q "Failed config"
  - cat home-assistant.log