###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Quebec
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 47
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: 
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - !secret externalDirShare
    - !secret externalDirTmp
    - !secret externalDirDafang
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.0.0/24
        - 192.168.1.0/24
        - 192.168.86.0/24
        - 192.168.86.100
#        - 216.98.48.0/20 # All Ubisoft
      allow_bypass_login: true
    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret http_password
  # https://www.home-assistant.io/docs/configuration/splitting_configuration/
  # https://www.home-assistant.io/docs/configuration/packages/
  # Splitted between integrations and entites as https://github.com/jonathanadams/Home-Assistant-Configuration
  packages: !include_dir_named integrations


####################################################
#        Home Assistant Components Enabled         #
####################################################
# https://www.home-assistant.io/components/system_health/
system_health:
# Show links to resources in log and frontend introduction: Enables the 
# frontend
frontend:
  javascript_version: latest

# https://www.home-assistant.io/components/config/
# Enables configuration UI
config:

# https://home-assistant.io/components/api/
api:
  
# https://www.home-assistant.io/components/history/
# Enables support for tracking state changes over time
history:

# https://www.home-assistant.io/components/recorder/
# Tracked history is kept for 368 days
recorder:

####################################################
#                     Logs                         #
####################################################
# https://www.home-assistant.io/components/logger/
# verbose logs
logger:
  default: error
  logs:
    homeassistant.components.camera: debug
    homeassistant.components.sensor.google_travel_time: debug
    homeassistant.components.device_tracker.google_maps: debug
    homeassistant.components.notify.slack: debug
    homeassistant.components.xiaomi_aqara: debug
    homeassistant.components.xiaomi: debug
    homeassistant.components.binary_sensor.xiaomi: debug
#    homeassistant.components.mqtt: debug
    homeassistant.custom_components.email: debug
    #pydeconz: debug
    #homeassistant.components.deconz: debug

####################################################
#            Sensors and components                #
####################################################
# Track the sun
sun:

# IFTTT
ifttt:
  key: !secret ifttt_APIKey
  
# Raspberry Pi Camera
camera:
  - platform: rpi_camera
    image_width: 3280
    image_height: 2464
    image_quality: 100 
    image_rotation: 180
    timelapse: 60000
#    file_path: ***REMOVED***   # aucune idée de pourquoi ça ne fonctionne pas
  - platform: generic
    name: Dafang camera
    username: root
    password: !secret dafangPassword
    authentication: basic
    still_image_url: !secret dafangImageUrl
    stream_source: !secret dafangStreamSource
    verify_ssl: false
    scan_interval: 5
#  - platform: xiaomi
#    name: Dafang camera
#    host: '***REMOVED***'
#    model: 'yi'
#    password: !secret dafangPassword
    
# Meteo
weather:
  - platform: darksky
    api_key: !secret darksky_APIKey
    mode: daily
  - platform: openweathermap
    api_key: !secret openweathermap_APIKey
    mode: freedaily
    # hourly also possible for 3 hours forecast, use freedaily for the daily with the free tier
 

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - Kitchen
      - Bathroom
      - Bedroom
      - Aurore's bedroom
      - Dining room
      - Living room
      - Aurore's zone
    initial: Select Input
  living_room_color:
    name: Which color do you want the livingroom to be in?
    options:
      - None
      - White
      - Purple
      - Pink
      - Blue
# Tests
  destination:
    name: destination
    options:
      - Home
      - Work
      - Garderie
  
sensor:
  - platform: version
#  - platform: command_line
#    name: Version
#    command: "/home/homeassistant/bin/hass --version"
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: ipv4_address
      - type: ipv6_address
      - type: processor_use
      - type: last_boot
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: wlan0
      - type: network_out
        arg: wlan0
      - type: throughput_network_in
        arg: wlan0
      - type: throughput_network_out
        arg: wlan0
      - type: packets_in
        arg: wlan0
      - type: packets_out
        arg: wlan0
      - type: process
        arg: hass
      - type: process
        arg: convert
  - platform: template
    sensors:
       dest_address:
         value_template: >-
            {%- if is_state("input_select.destination", "Home") -%}
              ***REMOVED***,***REMOVED***
            {%- elif is_state("input_select.destination", "Work") -%}
              ***REMOVED***
            {%- elif is_state("input_select.destination", "Parents") -%}
              ***REMOVED***
            {%- else -%}
              Unknown
            {%- endif %}
       nas_free_space:
         friendly_name: NAS free space
         value_template: "{{ states('sensor.sonarr_disk_space')|float/14 | round(2) }}"
         unit_of_measurement: 'TB'
       living_room_temparature_with_icon:
         friendly_name: "Salon"
         unit_of_measurement: '°C'
         device_class: 'temperature'
         value_template: "{{ states('sensor.living_room_temperature') }}"
         entity_picture_template: >-
           {% if states('sensor.living_room_temperature')|float > 30 %}
             mdi:fire
           {% elif states('sensor.living_room_temperature')|float < 15 %}
             mdi:snowflake-alert
           {% else %}
             mdi:thermometer
           {% endif %}
    # Dark sky
  - platform: darksky
    api_key: !secret darksky_APIKey
    language: en
    forecast: 1
    scan_interval: '00:15'
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
      - uv_index
      - moon_phase
  - platform: waze_travel_time
    name: "Me to destination"
    origin: ***REMOVED***,***REMOVED***
    destination: sensor.dest_address
    region: 'US'
    # Weather prediction
  - platform: yr
  - platform: openweathermap
    api_key: !secret openweathermap_APIKey
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - weather_code
    # Sonarr
  - platform: sonarr
    host: !secret NAS_IP
    api_key: !secret sonarr_APIKey
    unit: TB
    monitored_conditions:
      - series
      - upcoming
      - wanted
      - queue
      - diskspace
    days: 7
  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_APIKey
    host: !secret NAS_IP
    days: 7
    max: 10
    # Radarr
  - platform: radarr
    host: !secret NAS_IP
    api_key: !secret radarr_APIKey
    port: 17878
    monitored_conditions:
      - movies
      - upcoming
      - status
    days: 30
    #Google Wifi
  - platform: google_wifi
    # Waze travel time
  - platform: waze_travel_time
    name: Travel time to work (Waze)
    origin: ***REMOVED***,***REMOVED*** #TODO: secret
    destination: ***REMOVED***
    region: 'US'
    scan_interval: 5
    # Google maps travel time (Giom)
  - platform: google_travel_time
    name: Travel time to work (Gmap)
    api_key: !secret gmap_APIKey
    origin: ***REMOVED***,***REMOVED***
    destination: ***REMOVED***
    scan_interval: 60
    # Google maps travel time (Claire)
  - platform: google_travel_time
    name: Travel time to work (Claire)
    api_key: !secret gmap_APIKey
    origin: ***REMOVED***,***REMOVED***
    destination: ***REMOVED***
    options:
      mode: transit
      transit_routing_preference: less_walking
    scan_interval: 60
  - platform: ebox
    username: vg66
    password: !secret ebox_password
    monitored_variables:
     - before_offpeak_download
     - before_offpeak_upload
     - before_offpeak_total
     - offpeak_download
     - offpeak_upload
     - offpeak_total
     - download
     - upload
     - total
     - balance
     #- limit
     - usage
    scan_interval: 60
  - platform: moon
  - platform: uptime
  - platform: season
    type: astronomical
#  - platform: email
#    email: !secret gmailEmail
#    password: !secret gmailPassword
  # https://github.com/vmanuel/hacs-google-fit
  - platform: google_fit
    name: Google Fit
    client_id: !secret googleDeveloperClientID
    client_secret: !secret googleDeveloperSecret
  # https://www.home-assistant.io/integrations/airvisual/
  - platform: airvisual
    api_key: !secret airvisual_APIKey #TODO: secret
    show_on_map: false
    monitored_conditions:
      - us
  # https://www.home-assistant.io/integrations/waqi/
  - platform: waqi
    token: !secret waqi_APIKey #TODO: secret
    locations:
      - Beauce
  # https://www.home-assistant.io/integrations/history_stats
  - platform: history_stats
    name: Giom's time at work this week
    entity_id: person.Giom_2
    state: 'Ubisoft'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Giom's time at work last week
    entity_id: person.Giom_2
    state: 'Ubisoft'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 - 7 * 86400 }}'
    end: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  - platform: history_stats
    name: Claire's time at work this week
    entity_id: person.Claire_2
    state: 'Université'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Claire's time at work last week
    entity_id: person.Claire_2
    state: 'Université'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 - 7 * 86400 }}'
    end: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  # https://github.com/custom-components/sensor.untappd
  - platform: untappd
    username: !secret untappedUsername
    id: !secret untappedClientID
    secret: !secret untappedSecret
    
binary_sensor:
  - platform: aurora
  - platform: workday
    country: CA
    province: QC   
  - platform: template
    sensors:
       people_home:
         friendly_name: 'People Home'
         device_class: presence
         value_template: >
           {{ is_state('person.giom_2', 'home') or
              is_state('person.claire_2', 'home') }}

speedtestdotnet:
  server_id: 1993
  scan_interval:
    minutes: 15
  monitored_conditions:
    - ping
    - download
    - upload

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'fr'
# Yeelights
yeelight:
  devices:
    192.168.86.130:
      name: Solarium
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.86.131:
      name: Color
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.86.132:
      name: White
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.86.134:
      name: ColorV2 # TODO: rename to Canapé Droite (and in all automations and scenes as well)
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.86.135: #TODO: add it to all scenes and automations
      name: Canapé Gauche
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
        
media_player:
  # Google Cast
  - platform: cast
  #Emby
  - platform: emby
    host: !secret NAS_IP
    api_key: !secret emby_APIKey

device_tracker:
  # Google Map location sharing
  - platform: google_maps
    username: !secret google_account
    max_gps_accuracy: 1000
    new_device_defaults:
      track_new_devices: True
  - platform: nmap_tracker
    hosts: 192.168.86.100-109
    new_device_defaults:
      track_new_devices: True
  
# https://www.home-assistant.io/components/person/  
person:
  - name: Giom
    id: giom
    user_id: ***REMOVED***
    device_trackers:
      - device_tracker.cellGiom
      - device_tracker.op6
      - device_tracker.oneplus6_lan
      - device_tracker.google_maps_108886437999779306059
  - name: Claire
    id: claire
    user_id: ***REMOVED***
    device_trackers:
      - device_tracker.cellClaire
      - device_tracker.google_maps_116551309970452496819

notify:
  - platform: slack
    name: Slack
    api_key: !secret slack_APIKey
    default_channel: '#hass'
    
panel_iframe:
  slack:
    title: 'Slack'
    url: 'https://gi-home.slack.com/unreads/'
  sonarr:
    title: 'Sonarr'
    url: '***REMOVED***'
  utorrent:
    title: 'uTorrent'
    url: 'https://remote.bittorrent.com/'
    
weblink:
  entities:
    - name: Slack
      url: 'https://gi-home.slack.com/unreads/'
    - name: Sonarr
      url: '***REMOVED***'
      # Dafang conf: https://***REMOVED***/
    
group: !include groups.yaml
automation: !include_dir_merge_list automations/ 
script: !include scripts.yaml

shell_command:
  resize_sunrise_pic: mogrify -resize 1080x720 ***REMOVED***/last_sunrise.jpg
  create_daily_gif: 'convert -delay 20 -limit area 0 -resize 25% -loop 0 {rpi_camera_{{ now().strftime("%Y%m%d") }}-*_night.jpg,rpi_camera_{{ now().strftime("%Y%m%d") }}-*_day.jpg} {{ now().strftime("%Y%m%d") }}.gif'
  
#Xiaomi Aquara gateway and connected devices
# xiaomi_aqara:
#   discovery_retry: 10
#   gateways:
# #    - key: !secret xiaomiKey1 # First gateway bought, updated and thus less open to Hass
# #      host: ***REMOVED***
# #      mac: !secret xiaomiMac1
#     - key: !secret xiaomiKey2 # Second gateway that we try not to update
#       host: ***REMOVED***
#       mac: !secret xiaomiMac2
    
point:
  client_id: !secret point_clientID
  client_secret: !secret point_APItoken
  
habitica:
  - api_user: !secret habitica_userID
    api_key: !secret habitica_APItoken
    

withings:
  client_id: !secret withingsClientID
  client_secret: !secret withingsSecret
  profiles:
    - Guillaume ***REMOVED***
    - Aurore ***REMOVED***
    - Claire ***REMOVED***

####################################################
#                       Zones                      #
####################################################
# https://www.home-assistant.io/components/zone/
zone:
  - name: Université
    latitude: ***REMOVED***
    longitude: ***REMOVED***
    radius: 250
    icon: mdi:beaker

  - name: Ubisoft
    latitude: ***REMOVED***
    longitude: ***REMOVED***
    radius: 100
    icon: mdi:gamepad-variant
    
  - name: Garderie
    latitude: ***REMOVED***
    longitude: ***REMOVED***
    radius: 100
    icon: fas:baby

  # This will override the default home zone
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:home-circle
    
    
google:
  client_id: !secret googleDeveloperClientID
  client_secret: !secret googleDeveloperSecret
  
tplink:

mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant
  password: !secret mqttPassword

vacuum:
  - platform: xiaomi_miio
    host: 192.168.86.170
    token: !secret roborockToken

light:
  - platform: switch
    name: Cuisine
    entity_id: switch.lumiere_cuisine

scene: !include_dir_merge_list scenes

wake_on_lan:
switch:
  - platform: wake_on_lan
    name: Wake up PC
    mac: "***REMOVED***"
    host: ***REMOVED***
  - platform: wake_on_lan
    name: Wake up NAS
    mac: "***REMOVED***"
    host: ***REMOVED***

####################################################
#                 Work in progress                 #
####################################################