###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Cesson-Sévigné
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeLatitude
  longitude: !secret homeLongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 47
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml
  #  allowlist_external_dirs: #TODO: reaad external dirs
  #    - !secret externalDirShare
  #    - !secret externalDirTmp
  #    - !secret externalDirDafang
  external_url: !secret base_url
  internal_url: !secret internal_url
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.0.0/24 #TODO: secret?
        - 192.168.1.0/24
        - 192.168.86.0/24
        - 192.168.86.100
      #        - 216.98.48.0/20 # All Ubisoft
      allow_bypass_login: true
    - type: homeassistant
  #    - type: legacy_api_password
  #      api_password: !secret http_password
  # https://www.home-assistant.io/docs/configuration/splitting_configuration/
  # https://www.home-assistant.io/docs/configuration/packages/
  # Splitted between integrations and entites as https://github.com/jonathanadams/Home-Assistant-Configuration
  packages: !include_dir_named integrations

# things in default config that should be moved in integrations/
bluetooth:
dhcp:
energy:
hardware:
homeassistant_alerts:
media_source:
my:
ssdp:
usb:
zeroconf:

####################################################
#            Sensors and components                #
####################################################
binary_sensor:
  - platform: aurora
  - platform: workday
    country: FR
    #province: QC
  - platform: template
    sensors:
      people_home:
        friendly_name: "People Home"
        device_class: presence
        value_template: >
# Example configuration entry
template:
  - trigger:
      - platform: state
        entity_id: sensor.bleuette_ev_battery_level
    sensor:
      - name: "Bleuette autonomie max"
        unique_id: bleuette_max_autonomy
        unit_of_measurement: km
        state_class: measurement
        state: >
          {{ (states('sensor.bleuette_ev_range') | float / states('sensor.bleuette_ev_battery_level') | float * 100 ) | int }}
  # Pollens from Tomorrow.io (copied from https://community.home-assistant.io/t/uk-and-worldwide-pollen-count-using-tomorrow-io-api/306560)
  - sensor:
      - name: Pollen - Grass
        unique_id: sensor.pollen_grass
        state: "{{ states('sensor.pollen_grass_index_day_0') }}"
        icon: "mdi:grass"
        attributes:
          Today: "{{ states('sensor.pollen_grass_index_day_0') }}"
          Tomorrow: "{{ states('sensor.pollen_grass_index_day_1') }}"
          Today + 2: "{{ states('sensor.pollen_grass_index_day_2') }}"
          Today + 3: "{{ states('sensor.pollen_grass_index_day_3') }}"
          Today + 4: "{{ states('sensor.pollen_grass_index_day_4') }}"
      - name: Pollen - Tree
        unique_id: sensor.pollen_tree
        state: "{{ state_attr('sensor.pollen_grass_index_day_0', 'treeIndex') }}"
        icon: "mdi:tree"
        attributes:
          Today: "{{ state_attr('sensor.pollen_grass_index_day_0', 'treeIndex') }}"
          Tomorrow: "{{ state_attr('sensor.pollen_grass_index_day_1', 'treeIndex') }}"
          Today + 2: "{{ state_attr('sensor.pollen_grass_index_day_2', 'treeIndex') }}"
          Today + 3: "{{ state_attr('sensor.pollen_grass_index_day_3', 'treeIndex') }}"
          Today + 4: "{{ state_attr('sensor.pollen_grass_index_day_4', 'treeIndex') }}"
      - name: Pollen - Weed
        unique_id: sensor.pollen_weed
        state: "{{ state_attr('sensor.pollen_grass_index_day_0', 'weedIndex') }}"
        icon: "mdi:spa"
        attributes:
          Today: "{{ state_attr('sensor.pollen_grass_index_day_0', 'weedIndex') }}"
          Tomorrow: "{{ state_attr('sensor.pollen_grass_index_day_1', 'weedIndex') }}"
          Today + 2: "{{ state_attr('sensor.pollen_grass_index_day_2', 'weedIndex') }}"
          Today + 3: "{{ state_attr('sensor.pollen_grass_index_day_3', 'weedIndex') }}"
          Today + 4: "{{ state_attr('sensor.pollen_grass_index_day_4', 'weedIndex') }}"

# Pollens from Tomorrow.io (copied from https://community.home-assistant.io/t/uk-and-worldwide-pollen-count-using-tomorrow-io-api/306560)
rest:
  - resource: !secret tomorrow-api-pollen
    scan_interval: 3600
    sensor:
      ### Pollen - Tree Index
      - name: "Pollen - Grass Index - Day 0"
        value_template: "{{ value_json.data.timelines[0].intervals[0]['values']['grassIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[0].values"
        json_attributes:
          - treeIndex
          - weedIndex
          - grassIndex
          - grassGrassIndex
          - weedRagweedIndex
      - name: "Pollen - Grass Index - Day 1"
        value_template: "{{ value_json.data.timelines[0].intervals[1]['values']['grassIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[1].values"
        json_attributes:
          - treeIndex
          - weedIndex
          - grassIndex
          - grassGrassIndex
          - weedRagweedIndex
      - name: "Pollen - Grass Index - Day 2"
        value_template: "{{ value_json.data.timelines[0].intervals[2]['values']['grassIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[2].values"
        json_attributes:
          - treeIndex
          - weedIndex
          - grassIndex
          - grassGrassIndex
          - weedRagweedIndex
      - name: "Pollen - Grass Index - Day 3"
        value_template: "{{ value_json.data.timelines[0].intervals[3]['values']['grassIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[3].values"
        json_attributes:
          - treeIndex
          - weedIndex
          - grassIndex
          - grassGrassIndex
          - weedRagweedIndex
      - name: "Pollen - Grass Index - Day 4"
        value_template: "{{ value_json.data.timelines[0].intervals[4]['values']['grassIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[4].values"
        json_attributes:
          - treeIndex
          - weedIndex
          - grassIndex
          - grassGrassIndex
          - weedRagweedIndex
  - resource: !secret tomorrow-api-pollen-current
    scan_interval: 600
    sensor:
      ### Pollen - Tree Index
      - name: "Pollen - Current"
        value_template: "{{ value_json.data.timelines[0].intervals[0]['values']['grassIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[0].values"
        json_attributes:
          - treeIndex
          - weedIndex
          - grassIndex
          - grassGrassIndex
          - weedRagweedIndextree
          - AcaciaIndex
          - treeAshIndex
          - treeBeechIndex
          - treeBirchIndex
          - treeCedarIndex
          - treeCypressIndex
          - treeElderIndex
          - treeElmIndex
          - treeHemlockIndex
          - treeHickoryIndex
          - treeJuniperIndex
          - treeMahoganyIndex
          - treeMapleIndex
          - treeMulberryIndex
          - treeOakIndex
          - treePineIndex
          - treeCottonwoodIndex
          - treeSpruceIndex
          - treeSycamoreIndex
          - treeWalnutIndex
          - treeWillowIndex

# Yeelights
# yeelight:
#   devices:
#     192.168.86.130:
#       name: Solarium
#       transition: 1000
#       use_music_mode: False #(defaults to False)
#       save_on_change: False #(defaults to True)
#     192.168.86.131:
#       name: Color
#       transition: 1000
#       use_music_mode: True #(defaults to False)
#       save_on_change: False #(defaults to True)
#     192.168.86.132:
#       name: Freezer
#       transition: 1000
#       use_music_mode: False #(defaults to False)
#       save_on_change: False #(defaults to True)
#     192.168.86.134:
#       name: Canapé Droite
#       transition: 1000
#       use_music_mode: False #(defaults to False)
#       save_on_change: False #(defaults to True)
#     192.168.86.135:
#       name: Bedroom
#       transition: 1000
#       use_music_mode: False #(defaults to False)
#       save_on_change: False #(defaults to True)
#     192.168.86.136:
#       name: Canapé Gauche
#       transition: 1000
#       use_music_mode: False #(defaults to False)
#       save_on_change: False #(defaults to True)

media_player:
  # Google Cast
  - platform: cast
  #Emby
  #- platform: emby
  #  host: !secret NAS_IP
  #  api_key: !secret emby_APIKey

device_tracker:
  # Google Map location sharing
  - platform: google_maps
    username: !secret google_account
    max_gps_accuracy: 1000
    new_device_defaults:
      track_new_devices: True
  # - platform: nmap_tracker
  #   hosts: 192.168.86.100-109
  #   new_device_defaults:
  #     track_new_devices: True

# https://www.home-assistant.io/components/person/
person:
  - name: Giom
    id: giom
    user_id: !secret giomUserId
    device_trackers:
      - device_tracker.Pixel4XL
      - device_tracker.op6
      - device_tracker.oneplus6_lan
      - device_tracker.google_maps_108886437999779306059
  - name: Claire
    id: claire
    user_id: !secret claireUserId
    device_trackers:
      - device_tracker.cellClaire
      - device_tracker.google_maps_116551309970452496819

notify:
  - platform: slack
    name: Slack
    api_key: !secret slack_APIKey
    default_channel: "#hass"
  - name: SMS
    platform: free_mobile
    username: !secret freeMobileUsername
    access_token: !secret freeMobileToken

# Hangout https://www.home-assistant.io/integrations/hangouts/
hangouts:
  intents:
    HangoutsHelp:
      sentences:
        - Help
    LivingRoomTemperature:
      sentences:
        - What is the temperature in the living room
      conversations:
        - id: hangoutConversation
  default_conversations:
    - id: hangoutConversation
  error_suppressed_conversations:
    - id: hangoutConversation

# panel_iframe:
#   slack:
#     title: "Slack"
#     url: "https://gi-home.slack.com/unreads/"
#   sonarr:
#     title: "Sonarr"
#     url: !secret sonarrUrl
#   utorrent:
#     title: "uTorrent"
#     url: "https://remote.bittorrent.com/"

# weblink:
#   entities:
#     - name: Slack
#       url: 'https://gi-home.slack.com/unreads/'
#     - name: Sonarr
#       url: !secret sonarrUrl

shell_command:
  resize_sunrise_pic: mogrify -resize 1080x720 /home/homeassistant/.homeassistant/Share/last_sunrise.jpg
  create_daily_gif: 'convert -delay 20 -limit area 0 -resize 25% -loop 0 {rpi_camera_{{ now().strftime("%Y%m%d") }}-*_night.jpg,rpi_camera_{{ now().strftime("%Y%m%d") }}-*_day.jpg} {{ now().strftime("%Y%m%d") }}.gif'

####################################################
#                       Zones                      #
####################################################
# https://www.home-assistant.io/components/zone/
zone:
  - name: Université
    latitude: !secret universityLatitude
    longitude: !secret universityLongitude
    radius: 250
    icon: mdi:beaker

  - name: Ubisoft
    latitude: !secret ubisoftLatitude
    longitude: !secret ubisoftLongitude
    radius: 100
    icon: mdi:gamepad-variant

  - name: Google
    latitude: !secret googleLatitude
    longitude: !secret googleLongitude
    radius: 100
    icon: mdi:google

  - name: École
    latitude: !secret schoolLatitude
    longitude: !secret schoolLongitude
    radius: 100
    icon: mdi:school

  # This will override the default home zone
  - name: Home
    latitude: !secret homeLatitude
    longitude: !secret homeLongitude
    radius: 100
    icon: mdi:home-circle

# temporarily disabling the google calendar integration to fix the rest
#google:
#  client_id: !secret googleDeveloperClientID
#  client_secret: !secret googleDeveloperSecret

#tplink:

mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant
  password: !secret mqttPassword

# vacuum:
#   - platform: xiaomi_miio
#     host: !secret vaccumIP
#     token: !secret roborockToken

light:
  - platform: switch
    name: Cuisine
    entity_id: switch.lumiere_cuisine
  - platform: dlight
    host: 192.168.86.21
    device_id: E5b18418
####################################################
#                 Work in progress                 #
####################################################

# rest:
#   - resource: http://192.168.86.219:8249/state
#     binary_sensor:
#       - name: "In a meeting"
#         value_template: "{{ value_json.in_meeting }}"
