###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Quebec
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 47
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: 
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - !secret externalDirShare
    - !secret externalDirTmp
    - !secret externalDirDafang
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.0.0/24
        - 192.168.1.0/24
        - 192.168.86.0/24
        - 192.168.86.100
#        - 216.98.48.0/20 # All Ubisoft
      allow_bypass_login: true
    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret http_password
  # https://www.home-assistant.io/docs/configuration/splitting_configuration/
  # https://www.home-assistant.io/docs/configuration/packages/
  # Splitted between integrations and entites as https://github.com/jonathanadams/Home-Assistant-Configuration
  packages: !include_dir_named integrations


####################################################
#        Home Assistant Components Enabled         #
####################################################
# https://www.home-assistant.io/components/system_health/
system_health:
# Show links to resources in log and frontend introduction: Enables the 
# frontend
frontend:
  javascript_version: latest

# https://www.home-assistant.io/components/config/
# Enables configuration UI
config:

# https://home-assistant.io/components/api/
api:
  
# https://www.home-assistant.io/components/history/
# Enables support for tracking state changes over time
history:

# https://www.home-assistant.io/components/recorder/
# Tracked history is kept for 368 days
recorder:

####################################################
#            Sensors and components                #
####################################################
 

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - Kitchen
      - Bathroom
      - Bedroom
      - Aurore's bedroom
      - Dining room
      - Living room
      - Aurore's zone
    initial: Select Input
  living_room_color:
    name: Which color do you want the livingroom to be in?
    options:
      - None
      - White
      - Purple
      - Pink
      - Blue
# Tests
  destination:
    name: destination
    options:
      - Home
      - Work
      - Garderie
  
binary_sensor:
  - platform: aurora
  - platform: workday
    country: CA
    province: QC   
  - platform: template
    sensors:
       people_home:
         friendly_name: 'People Home'
         device_class: presence
         value_template: >
           {{ is_state('person.giom_2', 'home') or
              is_state('person.claire_2', 'home') }}

speedtestdotnet:
  server_id: 1993
  scan_interval:
    minutes: 15
  monitored_conditions:
    - ping
    - download
    - upload

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'fr'
# Cloud
#cloud: #TODO: home made server
# Yeelights
yeelight:
  devices:
    192.168.86.130:
      name: Solarium
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.86.131:
      name: Color
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.86.132:
      name: White
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.86.134:
      name: ColorV2
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
        
media_player:
  # Google Cast
  - platform: cast
  #Emby
  - platform: emby
    host: !secret NAS_IP
    api_key: !secret emby_APIKey

device_tracker:
  # Google Map location sharing
  - platform: google_maps
    username: !secret google_account
    max_gps_accuracy: 1000
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False
  - platform: nmap_tracker
    hosts: 192.168.86.100-109
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False
  
# https://www.home-assistant.io/components/person/  
person:
  - name: Giom
    id: giom
    user_id: ***REMOVED***
    device_trackers:
      - device_tracker.cellGiom
      - device_tracker.op6
      - device_tracker.oneplus6_lan
      - device_tracker.google_maps_108886437999779306059
  - name: Claire
    id: claire
    user_id: ***REMOVED***
    device_trackers:
      - device_tracker.cellClaire
      - device_tracker.google_maps_116551309970452496819

notify:
  - platform: slack
    name: Slack
    api_key: !secret slack_APIKey
    default_channel: '#hass'
    
panel_iframe:
  slack:
    title: 'Slack'
    url: 'https://gi-home.slack.com/unreads/'
  sonarr:
    title: 'Sonarr'
    url: '***REMOVED***'
  utorrent:
    title: 'uTorrent'
    url: 'https://remote.bittorrent.com/'
    
weblink:
  entities:
    - name: Slack
      url: 'https://gi-home.slack.com/unreads/'
    - name: Sonarr
      url: '***REMOVED***'
      # Dafang conf: https://***REMOVED***/
    
group: !include groups.yaml
automation: !include_dir_merge_list automations/ 
script: !include scripts.yaml

shell_command:
  resize_sunrise_pic: mogrify -resize 1080x720 ***REMOVED***last_sunrise.jpg
  create_daily_gif: 'convert -delay 20 -limit area 0 -resize 25% -loop 0 {rpi_camera_{{ now().strftime("%Y%m%d") }}-*_night.jpg,rpi_camera_{{ now().strftime("%Y%m%d") }}-*_day.jpg} {{ now().strftime("%Y%m%d") }}.gif'
  
#Xiaomi Aquara gateway and connected devices
# xiaomi_aqara:
#   discovery_retry: 10
#   gateways:
# #    - key: !secret xiaomiKey1 # First gateway bought, updated and thus less open to Hass
# #      host: ***REMOVED***
# #      mac: !secret xiaomiMac1
#     - key: !secret xiaomiKey2 # Second gateway that we try not to update
#       host: ***REMOVED***
#       mac: !secret xiaomiMac2
    
point:
  client_id: !secret point_clientID
  client_secret: !secret point_APItoken
  
habitica:
  - api_user: !secret habitica_userID
    api_key: !secret habitica_APItoken
    

withings:
  client_id: !secret withingsClientID
  client_secret: !secret withingsSecret
  profiles:
    - Guillaume ***REMOVED***
    - Aurore ***REMOVED***
    - Claire ***REMOVED***

####################################################
#                       Zones                      #
####################################################
# https://www.home-assistant.io/components/zone/
zone:
  - name: Université
    latitude: ***REMOVED***
    longitude: ***REMOVED***
    radius: 250
    icon: mdi:beaker

  - name: Ubisoft
    latitude: ***REMOVED***
    longitude: ***REMOVED***
    radius: 100
    icon: mdi:gamepad-variant
    
  - name: Garderie
    latitude: ***REMOVED***
    longitude: ***REMOVED***
    radius: 100
    icon: fas:baby

  # This will override the default home zone
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:home-circle
    
    
google:
  client_id: !secret googleDeveloperClientID
  client_secret: !secret googleDeveloperSecret
  
tplink:

mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant
  password: !secret mqttPassword

vacuum:
  - platform: xiaomi_miio
    host: 192.168.86.170
    token: !secret roborockToken

light:
  - platform: switch
    name: Cuisine
    entity_id: switch.lumiere_cuisine

scene: !include_dir_merge_list scenes

wake_on_lan:
switch:
  - platform: wake_on_lan
    name: Wake up PC
    mac: "***REMOVED***"
    host: ***REMOVED***
  - platform: wake_on_lan
    name: Wake up NAS
    mac: "***REMOVED***"
    host: ***REMOVED***