version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.11.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            touch fake.pem
            mv secrets.fake.yaml secrets.yaml
            python3.11 -m venv .
            source bin/activate
            pip3 install --pre --upgrade homeassistant
            hass -c . --script check_config --info all
